// Package k6gen renders a scenario Config into a runnable k6 script.
//
// Auth values are NEVER written into the script. The script reads them from
// __ENV at run time (k6's equivalent of process.env), which loadcannon sets
// on the k6 child process's environment block — never as CLI args, never on
// disk. See internal/runner for how the process is launched.
package k6gen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"text/template"

	"github.com/yousafkhamza/loadcannon/internal/config"
)

const tmplSrc = `// Auto-generated by loadcannon — do not edit by hand.
// Regenerate with: loadcannon gen-k6 --scenario <file> -o <out>
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  {{- if .Stages }}
  stages: [
    {{- range .Stages }}
    { duration: {{ .Duration | printf "%q" }}, target: {{ .Target }} },
    {{- end }}
  ],
  {{- else }}
  vus: {{ .VUs }},
  duration: {{ .Duration | printf "%q" }},
  {{- end }}
  {{- if .Thresholds }}
  thresholds: {
    {{- range $k, $v := .Thresholds }}
    {{ $k | printf "%q" }}: [{{ $v | printf "%q" }}],
    {{- end }}
  },
  {{- end }}
  {{- if .Insecure }}
  insecureSkipTLSVerify: true,
  {{- end }}
};

const BASE_URL = {{ .BaseURL | printf "%q" }};
{{- if .HostOverride }}
const HOST_OVERRIDE = {{ .HostOverride | printf "%q" }};
{{- end }}

// Resolved once per VU init from the k6 process environment — never hardcoded.
const AUTH_HEADER = __ENV.LOADCANNON_AUTH_HEADER || '';
const AUTH_VALUE  = __ENV.LOADCANNON_AUTH_VALUE  || '';
const AUTH_USER   = __ENV.LOADCANNON_AUTH_USER   || '';
const AUTH_PASS   = __ENV.LOADCANNON_AUTH_PASS   || '';

const scenarios = {{ .ScenariosJSON }};

// weighted random pick, mirrors the traffic-mix ratio set in the scenario file
function pick() {
  const total = scenarios.reduce((s, x) => s + x.weight, 0);
  let r = Math.random() * total;
  for (const s of scenarios) {
    if (r < s.weight) return s;
    r -= s.weight;
  }
  return scenarios[scenarios.length - 1];
}

export default function () {
  const s = pick();
  const url = BASE_URL + s.path;

  const headers = Object.assign({ 'Content-Type': 'application/json' }, s.headers || {});
  {{- if .HostOverride }}
  headers['Host'] = HOST_OVERRIDE;
  {{- end }}
  if (AUTH_HEADER && AUTH_VALUE) {
    headers[AUTH_HEADER] = AUTH_VALUE;
  }

  const params = { headers: headers };
  {{- if .UseBasicAuth }}
  params.auth = 'basic';
  const authedUrl = url.replace('://', '://' + AUTH_USER + ':' + AUTH_PASS + '@');
  {{- end }}

  let res;
  const body = s.body || null;
  {{- if .UseBasicAuth }}
  res = http.request(s.method, authedUrl, body, params);
  {{- else }}
  res = http.request(s.method, url, body, params);
  {{- end }}

  check(res, {
    [s.name + ' status ok']: (r) => r.status === s.expect_status,
  });

  sleep(Math.random() * 0.5);
}
`

type tmplData struct {
	Stages        []config.Stage
	VUs           int
	Duration      string
	Thresholds    map[string]string
	Insecure      bool
	BaseURL       string
	HostOverride  string
	ScenariosJSON string
	UseBasicAuth  bool
}

type scenarioJSON struct {
	Name         string            `json:"name"`
	Method       string            `json:"method"`
	Path         string            `json:"path"`
	Weight       int               `json:"weight"`
	Headers      map[string]string `json:"headers,omitempty"`
	Body         string            `json:"body,omitempty"`
	ExpectStatus int               `json:"expect_status"`
}

// Generate renders the k6 script text for the given config.
func Generate(c *config.Config) (string, error) {
	scenarios := make([]scenarioJSON, 0, len(c.Scenarios))
	for _, s := range c.Scenarios {
		body := s.Body
		if s.BodyFile != "" {
			// intentionally not reading the file here — kept as a documented
			// limitation: pass --body-inline through `loadcannon gen-k6` if
			// you need file bodies baked in, or reference a small literal
			// body in the scenario file for now.
			return "", fmt.Errorf("scenario %q: body_file is not yet inlined by gen-k6; use \"body\" with an inline JSON string instead", s.Name)
		}
		scenarios = append(scenarios, scenarioJSON{
			Name: s.Name, Method: s.Method, Path: s.Path, Weight: s.Weight,
			Headers: s.Headers, Body: body, ExpectStatus: s.ExpectStatus,
		})
	}
	sj, err := json.Marshal(scenarios)
	if err != nil {
		return "", err
	}

	data := tmplData{
		Stages:        c.Load.Stages,
		VUs:           c.Load.VUs,
		Duration:      c.Load.Duration,
		Thresholds:    c.Thresholds,
		Insecure:      c.Target.InsecureSkipVerify,
		BaseURL:       c.Target.URL,
		HostOverride:  c.Target.HostOverride,
		ScenariosJSON: string(sj),
		UseBasicAuth:  c.Auth.AuthMode == config.AuthBasic,
	}

	t, err := template.New("k6").Parse(tmplSrc)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
